### ISSUE TITLE
Hei, sopiiko tuote esim 2006 vuosimallin sähköpatterin säädettäväksi wifi-termostaatiksi?

### ISSUE THREAD

**Issue by JarkkoGithub** [oh2th/io.ohmigo#1]

**Comment by JarkkoGithub** [comment]
Säädettäväksi

**Comment by oh2th** [comment]
Ei toimi näin. Tää härpäke simuloi sitä termostaatin anturia. Käytännössä säädettävä vastus.

**Comment by JarkkoGithub** [comment]
> Ei toimi näin. Tää härpäke simuloi sitä termostaatin anturia. Käytännössä säädettävä vastus. 
> 

Kiitos
